from PyQt5.QtCore import QEasingCurve as Ease

EASING_FUNCTIONS: dict[str, Ease] = {
  "InSine": Ease.InSine,
  "OutSine": Ease.OutSine,
  "InOutSine": Ease.InOutSine,
  "InQuad": Ease.InQuad,
  "OutQuad": Ease.OutQuad,
  "InOutQuad": Ease.InOutQuad,
  "InCubic": Ease.InCubic,
  "OutCubic": Ease.OutCubic,
  "InOutCubic": Ease.InOutCubic,
  "InQuart": Ease.InQuart,
  "OutQuart": Ease.OutQuart,
  "InOutQuart": Ease.InOutQuart,
  "InQuint": Ease.InQuint,
  "OutQuint": Ease.OutQuint,
  "InOutQuint": Ease.InOutQuint,
  "InExpo": Ease.InExpo,
  "OutExpo": Ease.OutExpo,
  "InOutExpo": Ease.InOutExpo,
  "InCirc": Ease.InCirc,
  "OutCirc": Ease.OutCirc,
  "InOutCirc": Ease.InOutCirc,
  "InBack": Ease.InBack,
  "OutBack": Ease.OutBack,
  "InOutBack": Ease.InOutBack,
  "InElastic": Ease.InElastic,
  "OutElastic": Ease.OutElastic,
  "InOutElastic": Ease.InOutElastic,
  "InBounce": Ease.InBounce,
  "OutBounce": Ease.OutBounce,
  "InOutBounce": Ease.InOutBounce,
}
